### ISSUE TITLE
consider changing the KQL queries inside the PS script 

### ISSUE THREAD

**Issue by mezzofix** [TheCloudScout/sentinel-pricing#15]
According to https://azure.microsoft.com/en-us/pricing/details/microsoft-sentinel/   "data volume is measured by the volume of data that will be stored in **GB (10^9 bytes)**". Hence dividing the sum of Quantity (Size of data in Mbytes) by 1024 will not return the accurate billable data volume. Please consider changing the KQL query's inside the PS script to sum(Quantity) / 1000 instead of sum(Quantity) / 1024. 

Thanks !

**Comment by TheCloudScout** [comment]
@mezzofix nice find! I've made the required changes to the code. Thanks for contributing!

**Comment by mezzofix** [comment]
No worries, I appreciate the effort you have put into making all the stuff in this repo and sharing it - great stuff!
