### ISSUE TITLE
Error "An empty pipe element is not allowed."

### ISSUE THREAD

**Issue by rafalfitt** [TheCloudScout/sentinel-pricing#5]
Executed using PowerShell 5.1.22621.608:

PS C:\Users\xxx\Downloads\sentinel-pricing-main> .\powershell-script\AzSentinelPricingOptimizer.ps1
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:141 char:5
+     | where TimeGenerated > ago(31d) and TimeGenerated < ago(1d)
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:141 char:56
+     | where TimeGenerated > ago(31d) and TimeGenerated < ago(1d)
+                                                        ~
The '<' operator is reserved for future use.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:143 char:5
+     | where IsBillable == True
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:144 char:5
+     | summarize TotalGBytes =round(sum(Quantity/(1024)),2) by bin(Tim ...
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:144 char:80
+ ...  TotalGBytes =round(sum(Quantity/(1024)),2) by bin(TimeGenerated, 1d)
+                                                                     ~
Missing argument in parameter list.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:145 char:5
+     | summarize ['GBs/day'] =round(avg(TotalGBytes),2)
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:151 char:5
+     | where TimeGenerated < ago(30d)
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:151 char:27
+     | where TimeGenerated < ago(30d)
+                           ~
The '<' operator is reserved for future use.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:153 char:5
+     | where IsBillable == true
+     ~
An empty pipe element is not allowed.
At C:\Users\xxx\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:154 char:5
+     | summarize PayedRetentionGB = round(sum(Quantity) / 1024 , 0)
+     ~
An empty pipe element is not allowed.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : EmptyPipeElement

**Comment by RobbeVandenDaele** [comment]
Hi @rafalfitt,

This is because you ran the code with powershell version 5. If you run the code using powershell 7, the issue will be resolved. Fyi, command to install powershell 7: winget install microsoft.powershell

@TheCloudScout maybe consider adding a required version to the script?
#Requires -Version 7 
or even better:  #Requires -PSEdition Core

**Comment by rafalfitt** [comment]
well, I couldn't find any requirements, so I assumed it can run from anywhere... ¯\\\_(ツ)\_/¯

**Comment by TheCloudScout** [comment]
I wasn't aware of this. Thanks for pointing this out @RobbeVandenDaele and for the effort of creating a pull request!

I'm obviously no PowerShell expert.... Thanks for helping me making it better. :)

@rafalfitt sorry for the inconvenience. If you pull the latest version, you shouldn't be able to run it in Windows PowerShell anymore.
