### ISSUE TITLE
Please consider using Set-StrictMode

### ISSUE THREAD

**Issue by rafalfitt** [TheCloudScout/sentinel-pricing#6]
https://redmondmag.com/articles/2017/12/28/understanding-powershell-strictmode.aspx

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-7.3

**Comment by TheCloudScout** [comment]
I'm obviously not a PowerShell expert. It seems that by using strict mode I need to declare all my variables first?

If you think is is important, I'd like to encourage you to help me out by creating a pull request with the appropriate changes. This way we can both make this script better and to apply best practices. 

Thanks!
