### ISSUE TITLE
updateArmParameters should be of type bool

### ISSUE THREAD

**Issue by RobbeVandenDaele** [TheCloudScout/sentinel-pricing#7]
Hi, great script! An issue I faced is that the frist if-statement that checks if parameter $updateArmParameters is set to true always returns true even when it is set to $false because this paramater is of type String. When you change this to type bool the script successfully launches without providing any parameters.
```
[CmdletBinding()]
param (

    [Parameter (Mandatory = $false)]
    [String] $subscriptionId = "",

    [Parameter (Mandatory = $false)]
    [String] $updateArmParameters = $false,

    [Parameter (Mandatory = $false)]
    [String] $parametersFilePath = ""

)
```

**Comment by TheCloudScout** [comment]
Thanks Robbe for letting me know. I've approved the PR you've created.
