### ISSUE TITLE
Error "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by rafalfitt** [TheCloudScout/sentinel-pricing#9]
┖─ Querying for average daily data ingest...
  ┖─ Check if workspace is Sentinel enabled...
  ┖─ Gathering Log Analytics pricing tier recommendations...
  ┖─ Retrieve Sentinal SKU...
  ┖─ Gathering Sentinel pricing tier recommendations...
  ┖─ Checking data retention ...
     Data older than free retention (90d) ?...
  ┖─ Checking if Sku's needs changing...
InvalidOperation: C:\Users\WDAGUtilityAccount\Downloads\sentinel-pricing-main\powershell-script\AzSentinelPricingOptimizer.ps1:313
Line |
 313 |                  if ($currentSku.Equals($optimalSku)) {
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
     ✓ Microsoft Sentinel Sku is currently running optimal Sku

Powershell 7.3.0

<img width="734" alt="image" src="https://user-images.githubusercontent.com/36852431/203766168-ddafd030-92d3-4366-9519-6a0e38b72a09.png">

**Comment by TheCloudScout** [comment]
Hi @rafalfitt ,

Thanks for letting me know! First I noticed that the Sentinel sky "pay-as-you-go" actually has a `PerGB` value with a capital 'P'. So I corrected that. But I'm almost sure that this does not solve your issue.

Secondly, I'd like you to run the following lines of PowerShell to retrieve both the workspace Sku and the Sentinel Sku values:

```
$subscriptionId = "< YOUR SUBSCRIPTION ID >"
$workspaceName = "< YOUR WORKSPACE NAME >"

## Connect to Azure
Connect-AzAccount -SubscriptionId $subscriptionId

## Retrieve workspace properties
$workspace = Get-AzOperationalInsightsWorkspace | Where-Object { $_.Name -eq $workspaceName }

## Retrieve Sentinel solution details via API
$context = Get-AzContext
$profileClient = [Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient]::new([Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile)
$token = $profileClient.AcquireAccessToken($context.Subscription.TenantId)
$headers = @{
    "Authorization" = "Bearer $($token.AccessToken)"
    "Content-Type"  = "application/json"
}
$params = @{
    "Method"  = "Get"
    "Uri"     = "https://management.azure.com/subscriptions/$($context.Subscription.Id)/resourceGroups/$($workspace.ResourceGroupName)/providers/Microsoft.OperationsManagement/solutions/SecurityInsights($($workspace.Name))?api-version=2015-11-01-preview"
    "Headers" = $headers
}
$sentinelProperties = Invoke-RestMethod @params -UseBasicParsing

## Output results
$currentSku = $workspace.Sku
$currentSentinelSku = $sentinelProperties.properties.sku | Select-Object -ExpandProperty name

Write-Host "Your current 'currentSku' value is: $($currentSku)" -ForegroundColor Yellow
Write-Host "Your current 'currentSentinelSku' value is: $($currentSentinelSku)" -ForegroundColor Yellow
```

I assume the error is thrown because the $currentSku value was empty for some reason. If you run the above and post back the results, We'll know what the actually values are that were retrieved.

**Comment by TheCloudScout** [comment]
Hi @rafalfitt ,

I've made a couple of changes which might help you with this. 

* Firstly, I fixed a small typo where I used a lowercase 'p' for 'perGB', which should be with a capital 'P'. But I doubt this could be the reason for this error.
* Secondly, I've added some additional error handling in case one of a few variables stay "$null" or have an unexpected value. Please pull the most recent changes and try again. It might happen that the script tells you that some values were "$null". But it should continue and show a table at the end with all results and workspace details in a summary. Maybe you can reply me with a screenshot of that table? Thanks! <br><br>

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/29123012/203857274-97a97990-79d8-4869-90c3-aafc4a8bac28.png"><sub>_Example of table summary at the end of the run_</sub>

**Comment by rafalfitt** [comment]
> $sentinelProperties = Invoke-RestMethod @params -UseBasicParsing
Invoke-RestMethod: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2015-11-01-preview' is invalid. The supported versions are '2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}

**Comment by rafalfitt** [comment]
after changing the api-version:
> $sentinelProperties = Invoke-RestMethod @params -UseBasicParsing
Invoke-RestMethod: {"message":"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/{id-hidden}/resourceGroups/providers/Microsoft.OperationsManagement/solutions/SecurityInsights()?api-version=2022-09-01'."}

**Comment by rafalfitt** [comment]
but Microsoft.OperationsManagement shows API Version 2015-11-01-preview:
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/36852431/203939812-f8959f74-f1a4-49e5-ae2a-23eb08e68d11.png">

**Comment by rafalfitt** [comment]
BTW, just saying the script will not work in constrained language mode:

$profileClient = [Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient]::new([Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile)
InvalidOperation: Cannot create type. Only core types are supported in this language mode.

**Comment by rafalfitt** [comment]
the output from your debug script is
Your current 'currentSku' value is: standalone
Your current 'currentSentinelSku' value is: PerGB

**Comment by rafalfitt** [comment]
> the script doesn't handle the "standalone" SKU
https://www.shankuehn.io/post/switch-log-analytics-pricing-sku-it-can-be-done
https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs?WT.mc_id=enterprise-0000-shkuehn#legacy-pricing-tiers

Yes I noticed that from your results. I thought adding Sentinel on top of a "standalone" workspace was not allowed. Thanks for clarifying, and much thanks for the effort of submitting a PR!

**Comment by rafalfitt** [comment]
I have submitted https://github.com/TheCloudScout/sentinel-pricing/pull/12 to fix the issue.

**Comment by TheCloudScout** [comment]
Thanks to #12 the issue is indeed resolved.
